### ISSUE TITLE
Stand-alone LUT for radiance-BT

### ISSUE THREAD

**Issue by cjmerchant** [FIDUCEO/MMD_HARM#1]
In calc_radiance.py the look-up table for radiance to BT conversion and vice versa is read when reading a level 1 file. But working with an MMD, we will not be reading L1 files. 
Suggest we need
1. a LUT auxiliary netcdf that has the tables for all the avhrrs
lut_rad2bt = get_lut_rad2bt(instrument_identifier, path='path/to/the/directory/where/the/file/is)
2. rad2bt, bt2rad and dbtdrad  functions that work with the result of get_lut_rad2bt

**Comment by patternizer** [comment]
Agreed, thank you. This improvement will allow for the development of stand-alone functions to be coded.

**Comment by patternizer** [comment]
jmollard has added the functionality: read_in_LUT(),  rad2bt(),  bt2rad(), dbt_drad(), drad_da()
patternizer has added the count2rad() and back-end tests
