### ISSUE TITLE
calc_radiance.py error in the case nch = 12

### ISSUE THREAD

**Issue by cjmerchant** [FIDUCEO/MMD_HARM#2]
The coefficients read in seem to be the same as when nch = 11, which can't be right

**Comment by patternizer** [comment]
The coefficients are read in from Ralf's harmonisaiton files (one per channel (nch) with:
   
file_in = "FIDUCEO_Harmonisation_Data_" + str(nch) + ".nc"

For the 3.7 micron channel there are 27 coefficients (9 sensors x 3 coeffs).
For the 11 and 12 micron channels there are 36 coefficients (9 sensors x 4 coeffs).
