### ISSUE TITLE
Need to extrapolate LUT?

### ISSUE THREAD

**Issue by patternizer** [FIDUCEO/MMD_HARM#3]
When testing the radiance --> BT conversion for the 3.7 micron channel, the BTs are capped at low radiance. 

![image](https://user-images.githubusercontent.com/5902974/58847841-46004400-867c-11e9-8bf3-69e2b094032f.png)

**Comment by cjmerchant** [comment]
What is the horizontal axis and what spectral response function are we talking about? This looks like a resolved spectrum

**Comment by jmollard** [comment]
Is it low radiance Mike, or is it 0? 

If it's 0, then would we wouldn't be able to retrieve any BT at all (as it could be anything)

If it's non-zero, then is it less than the lowest radiance value in the rad -> BT look up table? Is so, then the python linear interpolation won't work as you'll be interpolating between a number (which is the 0th term in the LUT) and a minus infinity (as it won't get a -1th term). That would give you a NaN, and so wouldn't plot. The only way to resolve that would be to set a BT at 0.0 radiance in the LUT if there isn't already one, or increase the resolution of the LUT at lower radiances (which I suspect might not be possible).

**Comment by patternizer** [comment]
> What is the horizontal axis and what spectral response function are we talking about? This looks like a resolved spectrum

It is along-track index (nj). It's the output of applying measurement equation #106.

**Comment by patternizer** [comment]
> Is it low radiance Mike, or is it 0?
> 
> If it's 0, then would we wouldn't be able to retrieve any BT at all (as it could be anything)
> 
> If it's non-zero, then is it less than the lowest radiance value in the rad -> BT look up table? Is so, then the python linear interpolation won't work as you'll be interpolating between a number (which is the 0th term in the LUT) and a minus infinity (as it won't get a -1th term). That would give you a NaN, and so wouldn't plot. The only way to resolve that would be to set a BT at 0.0 radiance in the LUT if there isn't already one, or increase the resolution of the LUT at lower radiances (which I suspect might not be possible).

Thanks James, you're right - I had turned zeros into np.nan. Here is how the conversion looks on a full orbit:

![image](https://user-images.githubusercontent.com/5902974/58876273-75876e80-86c5-11e9-9fa1-4dcd80076261.png)
